CREATE TABLE BROJILO (
    ID INTEGER PRIMARY KEY,
    NAZIV VARCHAR(32)
);

CREATE TABLE EVIDENCIJAPOTROSNJE (
    USERID INTEGER NOT NULL,
    BROJILOID INTEGER NOT NULL,
    MESEC INTEGER NOT NULL,
    GRAD VARCHAR(32) NOT NULL,
    ZABELEZENAPOTROSNJA REAL NOT NULL
);

CREATE TABLE KORISNICI (
    USERID INTEGER PRIMARY KEY,
    USERNAME VARCHAR(32) NOT NULL UNIQUE,
    PASSWORD VARCHAR(32) NOT NULL,
    ADRESA VARCHAR(32) NOT NULL
);

CREATE TABLE KORISNIKBROJILO (
    USERID INTEGER NOT NULL,
    BROJILOID INTEGER NOT NULL,
    CONSTRAINT USERID_FK FOREIGN KEY(USERID) REFERENCES KORISNICI(USERID),
    CONSTRAINT BROJILOID_FK FOREIGN KEY(BROJILOID) REFERENCES BROJILO(ID)
);

SELECT *FROM KORISNICI;

INSERT into KORISNICI values(1, 'maja', '123', 'Puskinova 2');
COMMIT;